CONDITIONS = [

    # Core symptoms
    "anhedonia",
    "consummatory anhedonia",
    "anticipatory anhedonia",
    "motivational anhedonia",
    "severe anhedonia",
    "treatment-resistant anhedonia",
    "refractory anhedonia",
    "anhedonia biomarkers",
    "substance blockage anhedonia",
    "reward deficiency",
    "reward dysfunction",
    "reward circuit dysfunction",
    "reward prediction error",
    "reward sensitivity",
    "reward valuation depression",
    "reward responsiveness psychiatric disorders",
    "hedonic capacity",
    "hedonic tone",
    "hedonic blunting",
    "pleasure processing",
    "emotional blunting",
    "emotional numbness",
    "affective blunting",
    "affective flattening",
    "blank mind",
    "cognitive blunting",
    "avolition",
    "amotivation",
    "motivational deficit neurobiology",
    "depersonalization derealization neurobiology",
    "visual snow syndrome neurology",
    "brain fog neurobiology",
    "effort-based decision making",
    "effort-cost decision making depression",
    "psychomotor retardation depression",

    # Depression
    "treatment-resistant depression",
    "TRD",
    "ultra treatment-resistant depression",
    "refractory depression",
    "major depressive disorder anhedonia subtype",
    "MDD anhedonia",
    "PTSD anhedonia",
    "PTSD reward dysfunction",
    "trauma-induced anhedonia",
    "stress-induced anhedonia",
    "burnout anhedonia neurobiology",
    "anhedonia schizophrenia",
    "post-psychotic depression anhedonia",

    # Dopamine circuits
    "mesolimbic dopamine",
    "mesocortical dopamine",
    "dopamine dysfunction",
    "dopaminergic signaling",
    "dopamine transporter",
    "dopamine receptor D1",
    "dopamine receptor D2",
    "dopamine receptor D3",
    "dopamine synthesis",
    "dopamine release",
    "dopamine agonist",
    "dopamine agonists anhedonia",
    "dopamine biomarker",
    "dopamine supersensitivity",
    "ventral tegmental area",
    "nucleus accumbens",
    "ventral striatum hypoactivity",
    "medial forebrain bundle",
    "prefrontal cortex dopamine signaling",
    "lateral habenula",
    "ventral pallidum",
    "functional connectivity reward circuits",

    # Glutamate
    "NMDA receptor modulator",
    "NMDA hypofunction",
    "GluN2B",
    "GluN2B negative allosteric modulator",
    "glutamate dysregulation",
    "glutamatergic signaling",
    "AMPA receptor potentiation",
    "AMPA positive allosteric modulator",
    "ampakine",
    "mGluR2/3 antagonist",
    "synaptic plasticity depression",

    # Neuroplasticity
    "BDNF signaling",
    "brain-derived neurotrophic factor",
    "TrkB agonist",
    "mTOR pathway depression",
    "neuroplasticity enhancers",
    "psychoplastogens",
    "neuroplastogen",
    "dendritic spine loss stress",
    "neurogenesis hippocampus depression",
    "hippocampal atrophy depression",
    "synaptic density depression",

    # Ketamine / psychedelics / serotoninergics
    "ketamine mechanism antidepressant",
    "esketamine",
    "esketamine clinical trials",
    "arketamine",
    "hydroxynorketamine",
    "rapid antidepressant response ketamine",
    "oral ketamine depression",
    "AXS-05",
    "dextromethorphan bupropion",
    "psilocybin depression clinical trial",
    "psychedelics neuroplasticity",
    "psychedelic-induced hypomania",
    "5-HT2A receptor plasticity",
    "MDMA neurotoxicity",
    "post-MDMA syndrome",
    "serotonin neurotoxicity",
    "serotonergic dysfunction anhedonia",
    "serotonin dopamine interaction",
    "5-HT2A receptor",
    "5-HT2C receptor",
    "sigma-1 receptor agonists",
    "sigma-1 receptor neuroprotection",

    # Neuroinflammation / neuroimmune
    "neuroinflammation depression",
    "microglial activation brain",
    "microglia-mediated neuroimmune suppression",
    "astrocyte dysfunction depression",
    "oligodendrocyte abnormalities depression",
    "cytokines depression",
    "tumor necrosis factor alpha",
    "interleukin-6",
    "NLRP3 inflammasome",
    "immune-mediated anhedonia",
    "neuroimmune interactions brain",
    "neuroimmune dysfunction",
    "blood-brain barrier dysfunction",
    "autoimmune encephalitis psychiatric symptoms",
    "autoimmune neuropsychiatric syndrome",
    "neuronal autoantibodies",
    "NMDA receptor encephalitis",
    "VGKC antibodies",
    "GAD65 antibodies",
    "intravenous immunoglobulin",
    "plasmapheresis autoimmune brain",
    "therapeutic plasma exchange neuropsychiatric",
    "CCR5 neuroinflammation",
    "maraviroc",
    "mast cell activation syndrome neuropsychiatric",
    "MCAS",
    "histamine brain neurotransmission",
    "histaminergic system psychiatric disorders",
    "histamine H3 receptor",
    "H3 receptor antagonist",
    "glymphatic system",
    "purinergic signaling",
    "P2X7 receptor",
    "cell danger response",
    "cGAS-STING pathway",

    # Mitochondrial / energy
    "mitochondrial dysfunction brain",
    "mitochondria psychiatric disorders",
    "mitochondrial depression",
    "mitochondrial psychiatry",
    "mitochondrial therapeutics",
    "brain energy metabolism depression",
    "oxidative stress neurons",
    "elamipretide",
    "methylene blue",
    "methylene blue neuroprotection",

    # Metabolic / CSF / kynurenine
    "metabolic psychiatry",
    "insulin resistance brain",
    "cerebral glucose metabolism",
    "ketogenic diet",
    "cerebral blood flow depression",
    "BH4 deficiency neurotransmitters",
    "tetrahydrobiopterin dopamine synthesis",
    "Kuvan",
    "sapropterin BH4 neuropsychiatric",
    "homovanillic acid CSF depression",
    "CSF neurotransmitter metabolites lumbar puncture",
    "cerebrospinal fluid biomarkers",
    "kynurenine pathway depression",
    "quinolinic acid",
    "NAD+ neuropsychiatric",
    "beta-hydroxybutyrate",

    # Gut-brain / autonomic
    "gut-brain axis depression",
    "microbiome psychiatric disorders",
    "fecal microbiota transplant depression",
    "FMT psychiatric disorders",
    "rifaximin",
    "vagus nerve stimulation depression",
    "tVNS",
    "tVNS clinical trials depression",
    "dysautonomia neuropsychiatric",
    "autonomic nervous system dysfunction depression",

    # HPA axis / stress models
    "HPA axis dysregulation",
    "HPA axis anhedonia",
    "cortisol dysregulation",
    "cortisol reward system depression",
    "glucocorticoid signaling",
    "chronic stress neurobiology",
    "learned helplessness model",
    "chronic unpredictable stress model",
    "social defeat stress model",
    "animal models anhedonia",

    # Neuromodulation
    "deep brain stimulation depression",
    "DBS medial forebrain bundle",
    "DBS treatment-resistant depression",
    "medial forebrain bundle DBS",
    "subcallosal cingulate DBS",
    "anhedonia DBS",
    "transcranial magnetic stimulation depression",
    "SAINT protocol",
    "SAINT TMS protocol",
    "Stanford accelerated intelligent neuromodulation therapy",
    "theta burst stimulation depression",
    "ECT",
    "ECT neuroplasticity",
    "ECT anhedonia",
    "stellate ganglion block depression",
    "SGB",
    "neuromodulation anhedonia",
    "hyperbaric oxygen therapy depression",
    "photobiomodulation brain",

    # Drug-induced injury states
    "psychiatric drug-induced anhedonia",
    "medication-induced persistent anhedonia",
    "drug-induced neuropsychiatric disorder",
    "iatrogenic brain injury",
    "SSRI-induced apathy",
    "SSRI-induced emotional blunting",
    "post-SSRI syndrome",
    "PSSD",
    "post-SSRI sexual dysfunction",
    "SSRI withdrawal syndrome",
    "antidepressant discontinuation syndrome",
    "post-acute withdrawal syndrome",
    "PAWS neuropsychiatric",
    "antipsychotic-induced dopamine blockade",
    "antipsychotic-induced emotional blunting",
    "neuroleptic-induced deficit syndrome",
    "neuroleptic deficit syndrome",
    "antipsychotic withdrawal",
    "olanzapine neuropsychiatric adverse effects",
    "quetiapine adverse neuropsychiatric effects",
    "risperidone-induced anhedonia",
    "bupropion-induced anhedonia",
    "bupropion neurological adverse effects",
    "akathisia",
    "akathisia treatment",
    "persistent akathisia",
    "withdrawal akathisia",
    "post-finasteride syndrome",
    "PFS",
    "finasteride neurological effects",
    "5-alpha reductase inhibitor brain",
    "neurosteroid depletion anhedonia",
    "neurosteroid deficiency",
    "benzodiazepine withdrawal neurobiology",
    "benzodiazepine kindling",
    "kindling CNS sensitization",
    "central sensitization brain",
    "protracted withdrawal syndrome",

    # Long COVID / post-viral
    "long COVID neuropsychiatric symptoms",
    "post-COVID anhedonia",
    "long COVID anhedonia",
    "PASC",
    "SARS-CoV-2 neuropsychiatric",
    "COVID-19 neuroinflammation",
    "post-viral neuroinflammation",
    "COVID dopamine dysfunction",
    "carbon monoxide poisoning neuropsychiatric",

    # Sexual dysfunction
    "sexual dysfunction neurobiology",
    "sexual anhedonia",
    "genital numbness",
    "genital anesthesia",
    "pleasureless orgasm",
    "libido dopamine regulation",
    "endocrine effects psychiatric drugs",

    # Neurosteroids / GABA
    "neurosteroids depression",
    "neuroactive steroids",
    "neurosteroid signaling",
    "allopregnanolone",
    "allopregnanolone GABA depression",
    "zuranolone",
    "zuranolone GABA neurosteroid",
    "GABA-A neurosteroid modulation",
    "pregnenolone neuropsychiatry",
    "testosterone brain dopamine",
    "GABAergic dysfunction depression",
    "GABA and anhedonia",
    "KCC2",
    "depolarizing GABA",
    "FAAH inhibitor",
    "endogenous cannabinoids",

    # Opioid system
    "opioid system anhedonia",
    "kappa opioid receptor dysphoria",
    "kappa opioid receptor antagonist",
    "KOR",
    "dynorphin",
    "mu opioid receptor reward",
    "buprenorphine depression",
    "low dose naltrexone",
    "low dose naltrexone neuroinflammation",

    # Epigenetics / cellular stress
    "epigenetics depression",
    "gene expression reward circuitry",
    "histone deacetylase inhibitor",
    "integrated stress response",
    "eIF2alpha phosphorylation",
    "ISRIB",

    # Specific treatments
    "pramipexole",
    "pramipexole depression trial",
    "ropinirole",
    "MAOI",
    "MAOI treatment resistant depression",
    "monoamine oxidase inhibitor",
    "MAO-A inhibition depression",
    "tranylcypromine",
    "tranylcypromine anhedonia",
    "phenelzine",
    "phenelzine reward restoration",
    "isocarboxazid",
    "selegiline",
    "bupropion dopamine norepinephrine",
    "modafinil depression fatigue",
    "amantadine dopamine release",
    "amisulpride",
    "amisulpride low dose dopamine",
    "sulpiride antidepressant dopamine",
    "aripiprazole low dose depression",
    "vortioxetine mechanism anhedonia",
    "agomelatine melatonin depression",
    "tianeptine glutamate mechanism",
    "stimulants depression cognition",
    "bromantane",
    "anti-inflammatory depression",
    "enclomiphene",

    # Experimental / research compounds
    "TAK-653",
    "TAK-041",
    "GLYX-13",
    "rapastinel",
    "9-methyl-beta-carboline",
    "9-me-bc",
    "zalsupindole",
    "ACD856",
    "vorinostat",
    "tariquidar",
    "URB597",
    "GPR139 agonist",
    "NSI-189",
    "NSI-189 neurogenesis depression",
    "cerebrolysin",
    "cerebrolysin neuroprotection depression",
    "semax",
    "semax neuropeptide cognitive",
    "selank",
    "MIF-1",
    "BPC-157",
    "Dihexa",
    "semaglutide neuropsychiatry",
    "GLP-1 receptor brain",
    "melanocortin neuropsychiatric",
    "bremelanotide neurological adverse effects",
    "orexin agonist",
    "SERT-nNOS interaction",
    "RGS4",

    # Biomarkers / outcome measures
    "EEG biomarkers depression",
    "fMRI reward task depression",
    "PET imaging dopamine",
    "Snaith-Hamilton Pleasure Scale",
    "SHAPS",
    "effort expenditure for rewards task",
    "drug nonresponse",
    "loss of drug effects",
]
