import requests
import json
import os
from datetime import datetime, timedelta

BOT_TOKEN = os.environ.get("DISCORD_BOT_TOKEN", "")
CHANNEL_ID = "1510647038977773640"

CONDITIONS = [
"anhedonia",
"consummatory anhedonia",
"anticipatory anhedonia",
"motivational anhedonia",
"severe anhedonia",
"primary anhedonia",
"treatment-resistant anhedonia",
"refractory anhedonia",
"transdiagnostic anhedonia",
"anhedonia clinical trial",
"anhedonia treatment",
"anhedonia biomarkers",
"anhedonia blockage",
"substance blockage anhedonia",
"reward deficiency",
"reward dysfunction",
"reward processing",
"reward circuitry",
"reward circuit dysfunction",
"reward prediction error",
"reward sensitivity",
"reward valuation depression",
"reward responsiveness psychiatric disorders",
"reward biomarker",
"hedonic capacity",
"hedonic tone",
"hedonic blunting",
"hedonic capacity measurement",
"pleasure processing",
"emotional blunting",
"emotional numbness",
"affective blunting",
"affective flattening",
"blank mind",
"cognitive blunting",
"avolition",
"apathy",
"amotivation",
"motivational deficit neurobiology",
"brain fog",
"brain fog neurobiology",
"cognitive impairment",
"executive dysfunction",
"processing speed deficits",
"working memory deficits",
"working memory dopamine",
"cognitive control",
"psychomotor retardation depression",
"depersonalization derealization neurobiology",
"visual snow syndrome neurology",
"treatment-resistant depression",
"TRD",
"ultra treatment-resistant depression",
"refractory depression",
"major depressive disorder anhedonia subtype",
"MDD anhedonia",
"anhedonia schizophrenia",
"post-psychotic depression anhedonia",
"PTSD anhedonia",
"PTSD reward dysfunction",
"trauma-induced anhedonia",
"stress-induced anhedonia",
"burnout anhedonia neurobiology",
"mesolimbic dopamine",
"mesocortical dopamine",
"mesolimbic pathway",
"dopamine dysfunction",
"dopaminergic signaling",
"dopamine transporter",
"dopamine receptor D1",
"dopamine receptor D2",
"dopamine receptor D3",
"dopamine synthesis",
"dopamine release",
"dopamine plasticity",
"dopamine agonist",
"dopamine agonists anhedonia",
"dopamine biomarker",
"dopamine supersensitivity",
"ventral tegmental area",
"nucleus accumbens",
"ventral striatum",
"ventral striatum hypoactivity",
"dorsal striatum",
"caudate nucleus",
"putamen",
"medial forebrain bundle",
"orbitofrontal cortex",
"prefrontal cortex",
"medial prefrontal cortex",
"prefrontal cortex dopamine signaling",
"anterior cingulate cortex",
"subgenual cingulate",
"subcallosal cingulate gyrus",
"insula",
"amygdala",
"habenula",
"lateral habenula",
"hippocampus",
"ventral pallidum",
"dorsal raphe nucleus",
"prelimbic cortex",
"ventral premotor cortex",
"default mode network dysfunction",
"salience network dysfunction",
"salience network",
"functional connectivity reward circuits",
"brain network connectivity depression",
"connectomics psychiatric disorders",
"white matter integrity depression",
"effort-based decision making",
"effort-cost decision making depression",
"NMDA receptor antagonists",
"NMDA receptor modulator",
"NMDA hypofunction",
"GluN2B",
"GluN2B negative allosteric modulator",
"glutamate dysregulation",
"glutamatergic transmission",
"glutamatergic signaling",
"AMPA receptor potentiation",
"AMPA receptor potentiator",
"AMPA positive allosteric modulator",
"ampakine",
"mGluR2",
"mGluR3",
"mGluR5",
"mGluR2/3 antagonist",
"excitotoxicity",
"synaptic plasticity depression",
"long-term potentiation",
"BDNF",
"BDNF signaling",
"brain-derived neurotrophic factor",
"NTRK2",
"TrkB",
"TrkB agonist",
"CREB",
"mTOR pathway depression",
"mTORC1",
"neuroplasticity enhancers",
"psychoplastogens",
"neuroplastogen",
"neurite outgrowth",
"synaptogenesis",
"dendritic spine density",
"dendritic spine loss stress",
"cortical plasticity",
"neurogenesis hippocampus depression",
"hippocampal atrophy depression",
"structural brain changes antidepressants",
"synaptic density depression",
"ketamine",
"ketamine mechanism antidepressant",
"esketamine",
"esketamine clinical trials",
"norketamine",
"hydroxynorketamine",
"rapid antidepressant response ketamine",
"oral ketamine depression",
"psychedelics neuroplasticity",
"psychedelic therapy",
"psychedelic-induced hypomania",
"psilocybin depression clinical trial",
"5-HT2A receptor plasticity",
"LSD",
"DMT",
"ayahuasca",
"MDMA",
"MDMA neurotoxicity",
"post-MDMA syndrome",
"serotonin dopamine interaction",
"serotonergic dysfunction anhedonia",
"serotonin neurotoxicity",
"5-HT1A receptor",
"5-HT2A receptor",
"5-HT2C receptor",
"sigma-1 receptor",
"sigma-1 receptor agonists",
"sigma-1 receptor neuroprotection",
"neuroinflammation",
"neuroinflammation depression",
"microglial activation",
"microglial activation brain",
"microglia",
"microglia-mediated neuroimmune suppression",
"astrocyte activation",
"astrocyte dysfunction depression",
"reactive astrocytes",
"oligodendrocyte abnormalities depression",
"cytokines",
"cytokines depression",
"tumor necrosis factor alpha",
"interleukin-6",
"interferon gamma",
"C-reactive protein",
"NLRP3 inflammasome",
"NF-kappaB",
"immune-mediated anhedonia",
"neuroimmune interactions brain",
"brain immune signaling",
"neuroimmune dysfunction",
"neuroimmune biomarker",
"innate immunity",
"adaptive immunity",
"macrophage polarization",
"autoimmune encephalitis",
"autoimmune encephalitis psychiatric symptoms",
"autoimmune neuropsychiatric syndrome",
"neuronal autoantibodies",
"NMDA receptor encephalitis",
"VGKC antibodies",
"GAD65 antibodies",
"intravenous immunoglobulin",
"IVIG",
"plasmapheresis",
"plasmapheresis autoimmune brain",
"therapeutic plasma exchange neuropsychiatric",
"blood-brain barrier dysfunction",
"blood-brain barrier permeability",
"glymphatic system",
"neurovascular unit",
"neurovascular coupling dysfunction",
"mast cell activation syndrome",
"mast cell activation syndrome brain",
"mast cell activation syndrome neuropsychiatric",
"MCAS",
"mast cells",
"histamine intolerance",
"allergic neuroinflammation",
"histamine",
"histamine brain neurotransmission",
"histaminergic system psychiatric disorders",
"histamine H3 receptor",
"histamine H3 inverse agonist",
"H3 receptor antagonist",
"histaminergic signaling",
"betahistine",
"mitochondrial dysfunction",
"mitochondrial dysfunction brain",
"mitochondria psychiatric disorders",
"mitochondrial disease neuropsychiatric",
"mitochondrial medicine",
"mitochondrial bioenergetics",
"mitochondrial depression",
"mitochondrial psychiatry",
"mitochondrial therapeutics",
"mitochondrial biomarker",
"mitophagy",
"cardiolipin",
"ATP production neurons",
"oxidative phosphorylation",
"electron transport chain",
"bioenergetics brain function",
"brain energy metabolism depression",
"oxidative stress",
"oxidative stress neurons",
"nitrosative stress",
"redox signaling",
"glutathione",
"reactive oxygen species",
"ROS",
"metabolic psychiatry",
"metabolic brain disorders cognition",
"metabolic dysfunction",
"insulin resistance brain",
"cerebral glucose metabolism",
"metabolic biomarkers",
"ketogenic diet",
"lactate brain signaling",
"cerebral blood flow depression",
"BH4 deficiency",
"BH4 deficiency neurotransmitters",
"tetrahydrobiopterin",
"tetrahydrobiopterin dopamine synthesis",
"Kuvan",
"sapropterin BH4 neuropsychiatric",
"homovanillic acid",
"homovanillic acid CSF depression",
"HVA",
"CSF biomarkers",
"CSF neurotransmitter metabolites lumbar puncture",
"cerebrospinal fluid biomarkers",
"kynurenine pathway depression",
"neurotoxic metabolites kynurenine",
"quinolinic acid",
"gut-brain axis",
"gut-brain axis depression",
"microbiome",
"microbiome psychiatric disorders",
"gut dysbiosis",
"psychobiotics",
"fecal microbiota transplant",
"fecal microbiota transplant depression",
"FMT",
"FMT psychiatric disorders",
"rifaximin",
"intestinal permeability",
"gut inflammation",
"vagus nerve",
"vagus nerve dopamine regulation",
"vagus nerve stimulation",
"vagus nerve stimulation depression",
"tVNS",
"tVNS clinical trials depression",
"transcranial vagus nerve stimulation",
"vagal signaling",
"brain gut communication",
"autonomic nervous system",
"autonomic nervous system dysfunction depression",
"dysautonomia",
"dysautonomia neuropsychiatric",
"sympathetic overactivity",
"parasympathetic dysfunction",
"cell danger response",
"CDR",
"purinergic signaling",
"P2X7 receptor",
"extracellular ATP",
"ATP signaling",
"HPA axis",
"HPA axis dysregulation",
"HPA axis anhedonia",
"cortisol dysregulation",
"cortisol reward system depression",
"cortisol awakening response",
"glucocorticoid signaling",
"chronic stress neurobiology",
"learned helplessness",
"learned helplessness model",
"chronic unpredictable stress model",
"social defeat stress model",
"animal models anhedonia",
"deep brain stimulation",
"deep brain stimulation depression",
"DBS",
"DBS medial forebrain bundle",
"DBS treatment-resistant depression",
"medial forebrain bundle DBS",
"subcallosal cingulate DBS",
"anhedonia DBS",
"responsive neurostimulation",
"brain-computer interface",
"brain-computer interface depression",
"BCI",
"closed loop neuromodulation",
"transcranial magnetic stimulation",
"transcranial magnetic stimulation depression",
"TMS",
"SAINT TMS protocol",
"SAINT protocol",
"Stanford accelerated intelligent neuromodulation therapy",
"theta burst stimulation",
"theta burst stimulation depression",
"transcranial direct current stimulation",
"transcranial direct current stimulation depression",
"transcranial alternating current stimulation depression",
"electroconvulsive therapy",
"electroconvulsive therapy mechanisms",
"ECT",
"ECT neuroplasticity",
"ECT anhedonia",
"stellate ganglion block",
"stellate ganglion block depression",
"stellate ganglion block PTSD",
"SGB",
"hyperbaric oxygen therapy brain",
"hyperbaric oxygen therapy depression",
"photobiomodulation brain",
"neuromodulation anhedonia",
"brain stimulation anhedonia",
"psychiatric drug-induced anhedonia",
"medication-induced persistent anhedonia",
"drug-induced neuropsychiatric disorder",
"iatrogenic brain injury",
"psychotropic medication adverse effects",
"antidepressant discontinuation syndrome",
"post-acute withdrawal syndrome",
"PAWS neuropsychiatric",
"SSRI-induced apathy",
"SSRI-induced emotional blunting",
"post-SSRI syndrome",
"PSSD",
"post-SSRI sexual dysfunction",
"SSRI withdrawal syndrome",
"antipsychotic-induced dopamine blockade",
"antipsychotic-induced emotional blunting",
"neuroleptic-induced deficit syndrome",
"neuroleptic deficit syndrome",
"dopamine supersensitivity",
"antipsychotic withdrawal",
"olanzapine neuropsychiatric adverse effects",
"quetiapine adverse neuropsychiatric effects",
"risperidone-induced anhedonia",
"long-acting injectable antipsychotic adverse effects",
"bupropion-induced anhedonia",
"bupropion neurological adverse effects",
"akathisia",
"akathisia treatment",
"persistent akathisia",
"withdrawal akathisia",
"post-finasteride syndrome",
"PFS",
"finasteride neurological effects",
"5-alpha reductase inhibitor brain",
"5-alpha reductase",
"neurosteroid depletion anhedonia",
"neurosteroid deficiency",
"DHT",
"benzodiazepine withdrawal",
"benzodiazepine withdrawal neurobiology",
"benzodiazepine-induced cognitive dysfunction",
"benzodiazepine kindling",
"kindling",
"kindling CNS sensitization",
"central sensitization brain",
"protracted withdrawal syndrome",
"long COVID",
"long COVID neuropsychiatric symptoms",
"post-COVID anhedonia",
"long COVID brain fog",
"long COVID anhedonia",
"post-acute sequelae of COVID",
"PASC",
"SARS-CoV-2 neuropsychiatric",
"COVID-19 neuroinflammation",
"post-viral neuroinflammation",
"COVID dopamine dysfunction",
"sexual dysfunction neurobiology",
"sexual anhedonia",
"genital numbness",
"genital anesthesia",
"erectile dysfunction",
"libido loss",
"pleasureless orgasm",
"libido dopamine regulation",
"endocrine effects psychiatric drugs",
"testosterone brain dopamine",
"neurosteroids",
"neurosteroids depression",
"neuroactive steroids",
"neurosteroid signaling",
"allopregnanolone",
"allopregnanolone GABA depression",
"allopregnanolone deficiency",
"zuranolone",
"zuranolone GABA neurosteroid",
"GABA-A neurosteroid modulation",
"pregnenolone",
"pregnenolone neuropsychiatry",
"endogenous cannabinoids",
"anandamide",
"FAAH inhibitor",
"GABAergic dysfunction depression",
"GABAergic transmission",
"GABA and anhedonia",
"GABA-A receptor",
"chloride homeostasis",
"transmembrane chloride gradient",
"KCC2",
"K+-Cl- cotransporter 2",
"SLC12A5",
"depolarizing GABA",
"opioid system anhedonia",
"kappa opioid receptor dysphoria",
"kappa opioid receptor antagonist",
"KOR",
"dynorphin",
"mu opioid receptor reward",
"buprenorphine depression",
"low dose naltrexone",
"low dose naltrexone neuroinflammation",
"epigenetics depression",
"gene expression reward circuitry",
"histone deacetylase inhibitor",
"HDAC inhibitor",
"SIRT2",
"SIRT2 inhibition",
"SIRT3",
"sirtuins",
"nicotinamide adenine dinucleotide",
"NAD+",
"epigenetic modification",
"integrated stress response",
"ISR",
"eIF2alpha phosphorylation",
"cGAS-STING pathway",
"pramipexole",
"pramipexole depression trial",
"ropinirole",
"bromocriptine",
"cabergoline",
"MAOI",
"MAOI treatment resistant depression",
"monoamine oxidase inhibitor",
"MAO-A inhibition depression",
"tranylcypromine",
"tranylcypromine anhedonia",
"phenelzine",
"phenelzine reward restoration",
"isocarboxazid",
"bupropion",
"bupropion dopamine norepinephrine",
"modafinil",
"modafinil depression fatigue",
"armodafinil",
"amantadine",
"amantadine dopamine release",
"amisulpride",
"amisulpride low dose dopamine",
"sulpiride",
"sulpiride antidepressant dopamine",
"aripiprazole",
"aripiprazole low dose depression",
"brexpiprazole",
"vortioxetine",
"vortioxetine mechanism anhedonia",
"agomelatine",
"agomelatine melatonin depression",
"tianeptine",
"tianeptine glutamate mechanism",
"methylphenidate",
"amphetamine",
"lisdexamfetamine",
"selegiline",
"rasagiline",
"safinamide",
"bromantane",
"infliximab",
"anti-inflammatory depression",
"lithium",
"lamotrigine",
"valproate",
"stimulants depression cognition",
"ALTO-203",
"ALTO-202",
"ALTO-300",
"ACI-7104",
"TAK-653",
"TAK-041",
"CX1739",
"XEN1101",
"GLYX-13",
"rapastinel",
"perampanel",
"suramin",
"elamipretide",
"ISRIB",
"9-methyl-beta-carboline",
"9-me-bc",
"beta-carbolines",
"zalsupindole",
"ACD856",
"AK-7",
"vorinostat",
"beta-hydroxybutyrate",
"tariquidar",
"URB597",
"ZZL-7",
"GPR139",
"GPR139 agonist",
"orphan GPCR",
"P-glycoprotein inhibitor",
"ABCB1",
"CYP3A5*3",
"NSI-189",
"NSI-189 neurogenesis depression",
"cerebrolysin",
"cerebrolysin neuroprotection depression",
"Cortexin",
"semax",
"semax neuropeptide cognitive",
"selank",
"selank anxiolytic neuropeptide",
"MIF-1",
"MIF-1 melanocyte inhibiting factor",
"BPC-157",
"Neboglamine",
"Dihexa",
"methylene blue",
"methylene blue neuroprotection",
"NAD+ neuropsychiatric",
"IV NAD+ therapy depression",
"inosine",
"semaglutide neuropsychiatry",
"GLP-1 receptor brain",
"oxytocin dopamine interaction",
"neuropeptides reward regulation",
"melanocortin system brain",
"MC4 receptor behavior",
"bremelanotide neurological adverse effects",
"melanocortin receptor agonist adverse effects",
"orexin",
"hypocretin",
"orexin agonist",
"wakefulness circuits",
"SERT-nNOS interaction",
"USP33",
"PRKN",
"parkin",
"SLC25A51",
"RGS4",
"G-protein signaling regulator",
"precision psychiatry",
"precision psychiatry biomarkers",
"precision medicine depression",
"biomarker guided psychiatry",
"EEG biomarkers depression",
"EEG biomarker",
"theta/beta ratio",
"fMRI reward task depression",
"PET imaging dopamine",
"electrophysiology biomarkers",
"functional MRI biomarkers",
"computational psychiatry reward learning",
"reinforcement learning models depression",
"pharmacodynamic biomarkers antidepressants",
"Snaith-Hamilton Pleasure Scale",
"SHAPS",
"Chapman Physical Anhedonia Scale",
"Temporal Experience of Pleasure Scale",
"effort expenditure for rewards task",
"clinical trials anhedonia endpoint",
"novel antidepressants",
"rapid acting antidepressants",
"mechanism based psychiatry",
"experimental psychiatry",
"transcriptomics depression brain",
"proteomics psychiatric disorders",
"single-cell RNA sequencing brain depression",
"cell-type specific changes depression",
"human brain organoid depression models",
"carbon monoxide poisoning neuropsychiatric",
"inhalant exposure brain injury",
"neuroregeneration",
"brain repair",
"astrocyte dysfunction depression",
"oligodendrocyte abnormalities depression",
"novel antidepressant mechanisms",
"psychoplastogens",
"ion channel dysfunction neurons",
"calcium signaling neurons",
"drug nonresponse",
"loss of drug effects",

]

DAYS_BACK = 1
SEEN_FILE = "seen_trials.json"

CONDITION_COLORS = {
    "anhedonia": 0x4A90D9,
    "major depression": 0x5B6EF5,
    "treatment resistant depression": 0x7B5EA7,
    "treatment resistant anhedonia": 0x9B59B6,
    "emotional blunting": 0x3498DB,
    "reward processing": 0x1ABC9C,
    "apathy": 0x95A5A6,
    "depersonalization": 0xE67E22,
    "derealization": 0xE74C3C,
    "cognitive dysfunction": 0x2ECC71,
    "executive dysfunction": 0x27AE60,
    "purinergic": 0xF39C12,
}

def load_seen():
    if os.path.exists(SEEN_FILE):
        with open(SEEN_FILE) as f:
            return set(json.load(f))
    return set()

def save_seen(seen):
    with open(SEEN_FILE, "w") as f:
        json.dump(list(seen), f)

def fetch_trials(condition):
    min_date = (datetime.now() - timedelta(days=DAYS_BACK)).strftime("%Y-%m-%d")
    url = "https://clinicaltrials.gov/api/v2/studies"
    params = {
    "query.cond": condition,
    "filter.advanced": f"AREA[StudyFirstPostDate]RANGE[{min_date}, MAX] AND AREA[LocationCountry](United States OR United Kingdom OR Germany OR France OR Italy OR Spain OR Netherlands OR Belgium OR Sweden OR Denmark OR Norway OR Finland OR Switzerland OR Austria OR Poland)",
    "fields": "NCTId,BriefTitle,Condition,Phase,StudyType,OverallStatus,StartDate,BriefSummary,LeadSponsorName,LocationCountry",
    "pageSize": 20,
    "sort": "StudyFirstPostDate:desc"
}
    try:
        response = requests.get(url, params=params, timeout=15)
        response.raise_for_status()
        return response.json().get("studies", [])
    except Exception as e:
        print(f"Error fetching '{condition}': {e}")
        return []

def post_to_discord(trial, matched_condition):
    s = trial.get("protocolSection", {})
    id_mod = s.get("identificationModule", {})
    status_mod = s.get("statusModule", {})
    desc_mod = s.get("descriptionModule", {})
    design_mod = s.get("designModule", {})
    sponsor_mod = s.get("sponsorCollaboratorsModule", {})
    contacts_mod = s.get("contactsLocationsModule", {})

    nct_id = id_mod.get("nctId", "N/A")
    title = id_mod.get("briefTitle", "No title")
    phase = ", ".join(design_mod.get("phases", ["Not specified"]))
    status = status_mod.get("overallStatus", "N/A")
    study_type = design_mod.get("studyType", "N/A")
    sponsor = sponsor_mod.get("leadSponsor", {}).get("name", "N/A")
    summary = desc_mod.get("briefSummary", "No summary available.")
    if len(summary) > 350:
        summary = summary[:350].rsplit(" ", 1)[0] + "…"

    locations = contacts_mod.get("locations", [])
    countries = list(set(loc.get("country", "") for loc in locations if loc.get("country")))
    country_str = ", ".join(countries[:5]) if countries else "Not specified"

    embed = {
        "title": f"🔬 {title}",
        "url": f"https://clinicaltrials.gov/study/{nct_id}",
        "color": 0x0057b7,
        "description": summary,
        "fields": [
            {"name": "🏷️ Matched Condition", "value": matched_condition.title(), "inline": True},
            {"name": "📋 NCT ID", "value": nct_id, "inline": True},
            {"name": "⚗️ Phase", "value": phase, "inline": True},
            {"name": "📊 Status", "value": status, "inline": True},
            {"name": "🔭 Study Type", "value": study_type, "inline": True},
            {"name": "🏢 Sponsor", "value": sponsor, "inline": True},
            {"name": "🌍 Countries", "value": country_str, "inline": False},
        ],
        "footer": {"text": "ClinicalTrials.gov • New Trial Alert"},
        "timestamp": datetime.utcnow().isoformat() + "Z"
    }

    headers = {
        "Authorization": f"Bot {BOT_TOKEN}",
        "Content-Type": "application/json"
    }
    payload = {"embeds": [embed]}
    try:
        r = requests.post(
            f"https://discord.com/api/v10/channels/{CHANNEL_ID}/messages",
            headers=headers,
            json=payload,
            timeout=10
        )
        r.raise_for_status()
    except Exception as e:
        print(f"Discord post failed for {nct_id}: {e}")

def run():
    seen = load_seen()
    posted = 0
    new_seen = set()

    for condition in CONDITIONS:
        print(f"Checking: {condition}")
        trials = fetch_trials(condition)
        for trial in trials:
            nct_id = trial.get("protocolSection", {}).get("identificationModule", {}).get("nctId")
            if not nct_id or nct_id in seen or nct_id in new_seen:
                continue  # Skip duplicates across conditions
            post_to_discord(trial, condition)
            new_seen.add(nct_id)
            posted += 1

    save_seen(seen | new_seen)
    print(f"Done. Posted {posted} new trial(s).")

if __name__ == "__main__":
    run()
